version: '3.3'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_weather
    restart: always
    ports:
      - 8001:80
    volumes:
      - ./src/weather_api:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel_weather
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_weather
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: 'serverName=weather_api'
    volumes:
      - ./src/weather_api:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      # - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - 9001:80
    networks:
      - laravel_weather

networks:
  laravel_weather:
